// Generated by Bunker Self-Hosted Compiler
#include "runtime.h"

// String Concatenation Helper
char* BNK_RT_Strings_concat(void* _self, char* s1, char* s2) {
    if (!s1) s1 = "";
    if (!s2) s2 = "";
    size_t len1 = strlen(s1);
    size_t len2 = strlen(s2);
    char* result = gc_alloc(len1 + len2 + 1);
    strcpy(result, s1);
    strcat(result, s2);
    return result;
}

// Int to String Helper
char* BNK_RT_Strings_fromInt(void* _self, long long n) {
    char* s = gc_alloc(32);
    sprintf(s, "%lld", n);
    return s;
}

// Generic Method Call Stub
void* MethodCall_Generic(void* obj, char* name) {
    printf("Error: Generic method call to %s not implemented in self-hosted bootstrap\n", name);
    return NULL;
}

// Module: test
// Entity: Person
struct Person {
    char* type;
    char* name;
    long long age;
};
struct Person* Person_new(void* _self, char* name, long long age) {
    struct Person* self = (struct Person*)_self;
struct Person* p = (struct Person*)gc_alloc(sizeof(struct Person))    ;
p->name = name    ;
p->age = age    ;
return p    ;
}
void Person_greet(void* _self) {
    struct Person* self = (struct Person*)_self;
printf("%s\n", (char*)BNK_RT_Strings_concat(NULL, "Hello, my name is ", self->name))    ;
printf("%s\n", (char*)BNK_RT_Strings_concat(NULL, BNK_RT_Strings_concat(NULL, "I am ", BNK_RT_Strings_fromInt(NULL, self->age)), " years old"))    ;
}
// Entity: Main
struct Main {
    char* type;
};
void Main_main(void* _self) {
    struct Main* self = (struct Main*)_self;
struct Person* p = Person_new(NULL, "Alice", 30)    ;
    ;
Person_greet(p)    ;
printf("%s\n", (char*)BNK_RT_Strings_concat(NULL, "Direct access: ", p->name))    ;
}

int main(int argc, char** argv) {
    volatile void* dummy; gc_stack_bottom = (void*)&dummy;
    GC_INIT();
    Main_main(NULL);
    return 0;
}
