--- Bunker Self-Hosted Lexer & Parser v0.3 ---
Reading file: tests/hello.bnk
File read, length: 176
Initializing Lexer...
Lexer initialized.
Collecting tokens...
Tokens collected: 36
Tokens collected
DEBUG: Parser initialized with 35 tokens
DEBUG: parseCall ':' nt.type=STRING value=Hello from self-hosted Bunker!
DEBUG: created LiteralExpr STR val=Hello from self-hosted Bunker!
DEBUG: created LiteralExpr NUM val=0
DEBUG: Creating method main
Parsing successful!
AST Structure:
 - Stmt Type: ModuleDecl
 - Stmt Type: EntityDecl

Running Type Checker...
Type Checking Program...
Type Checking Complete.
Generating C Code...
DEBUG: emitStatement type=ModuleDecl
DEBUG: emitStatement type=EntityDecl
DEBUG: emitStatement type=ExprStmt
DEBUG: emitExpression type=MethodCall
DEBUG: emitStatement type=MethodCall
DEBUG: emitExpression type=LiteralExpr
DEBUG: emitStatement type=LiteralExpr
DEBUG: emitLiteral val='Hello from self-hosted Bunker!' type=string
DEBUG: emitLiteral val='Hello from self-hosted Bunker!' type=string
DEBUG: emitStatement type=ReturnStmt
DEBUG: emitExpression type=LiteralExpr
DEBUG: emitStatement type=LiteralExpr
DEBUG: emitLiteral val='0' type=int
--- Generated C Code ---
// Generated by Bunker Self-Hosted Compiler
#include "runtime.h"

// Module: hello
// Entity: Main
struct Main {
    char* type;
};
long long Main_main(void* _self, long long argc, void* argv) {
    struct Main* self = (struct Main*)_self;
printf("%s\n", (char*)"Hello from self-hosted Bunker!")    ;
return 0    ;
}

int main(int argc, char** argv) {
    volatile void* dummy; gc_stack_bottom = (void*)&dummy;
    GC_INIT();
    return Main_main(NULL, argc, (void**)argv);
}

------------------------
Saved to: tests/hello.bnk.c
