// Generated by Bunker Self-Hosted Compiler
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <stdint.h>

typedef void* (*BunkerFunc)();
void gc_free(void* ptr);

// Module: hello_world
// Entity: Hello_worldApp
struct Hello_worldApp {
    char* type;
};
void Hello_worldApp_main(void* _self) {
    struct Hello_worldApp* self = (struct Hello_worldApp*)_self;
printf("%s\n", (char*)"Hello, Bunker v2.6.0!")    ;
}

int main(int argc, char** argv) {
    GC_INIT();
    return 0;
}
